baseURL = "https://lucaspereira.dev/"
languageCode = "en-us"
title = "Blog"
summary = "Backend Engineer | Thoughts on Technology and Programming"
theme = "paper"

contentDir = "content"

[params]
subtitle = 'The Best Widgets on Earth'
github = "lucaspere"
twitter = "lucaspereira"
linkedin = "lucasfapereira"
description = "Backend Engineer | Thoughts on Technology and Programming"
name = "Lucas Pereira"
bio = "Backend Engineer | Thoughts on Technology and Programming"
comments = true

[params.contact]
email = 'lucasfapereira@gmail.com'

[params.giscus]
repo = 'lucaspere/blog'
repoId = 'R_kgDONGVdbQ'
reactionsEnabled = true
emitMetadata = false
inputPosition = 'bottom'
theme = 'dark'
lang = 'en'
crossorigin = 'anonymous'
category = 'General'
categoryId = 'DIC_kwDONGVdbc4CjuIe'
mapping = 'pathname'

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
