baseURL = "https://lucaspereira.dev/"
languageCode = "en-us"
title = "Blog"
summary = "Backend Engineer | Thoughts on Technology and Programming"
theme = "paper"

contentDir = "content"

[params]
subtitle = 'The Best Widgets on Earth'
github = "lucaspere"
twitter = "lucaspereira"
linkedin = "lucasfapereira"
description = "Backend Engineer | Thoughts on Technology and Programming"
name = "Lucas Pereira"
bio = "Backend Engineer | Thoughts on Technology and Programming"
comments = true

[params.contact]
email = 'lucasfapereira@gmail.com'

[params.giscus]
repo = 'YOUR_GISCUS_REPO'              # see https://giscus.app for more details
repoId = 'YOUR_GISCUS_REPO_ID'
category = 'YOUR__GISCUS_CATEGORY'
categoryId = 'YOUR_GISCUS_CATEGORY_ID'
mapping = 'pathname'
theme = 'light'
lang = 'zh-CN'

[menu]
[[menu.main]]
url = "/"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/posts/"
weight = 20

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
